apiVersion: apps/v1
kind: Deployment
metadata:
  name: test 
  labels:
    app: web
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: wmp
          image: 711208530951.dkr.ecr.us-west-2.amazonaws.com/map_wmp:latest
          envFrom:
          - secretRef:
              name: mysecret
          ports:
            - containerPort: 8080
